- name: varaibles preferences
  hosts: frontend
  vars:
    full_name: "Siva from play"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: full_name
      prompt: "Please enter your full name"
      private: false
  tasks:
  - name: print vars preferences
    vars:
        full_name: "Siva from task"
    debug:
        msg: "Hi, {{full_name}}"
