[frontend]
172.31.26.54 ;COURSE="Ansible host vars NODE-1" # These are called as individual host vars
;172.31.26.48 ;COURSE="Ansible host vars NODE-2"  # second instance of frontend services

[catalogue]
172.31.27.249

[user]
172.31.27.250

[cart]
172.31.27.251

[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

; local group vars
; [local:vars]
; COURSE="Ansible"
; TRAINER="Sivakumar"
; DURATION="10HRS"

; frontend group vars
; [frontend:vars]
; COURSE="Ansible" # group vars for frontend services
; TRAINER="Sivakumar"
; DURATION="10HRS"
